name: Protect branches

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Protect branches
        run: go run main.go
        env:
          ORG: virsas
          USER: smoravcik
          TOKEN: ${{ secrets.TOKEN_GITHUB }}
